package disk

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"qvmhub/service/libvirt_rpc"

	"github.com/digitalocean/go-libvirt"
)

// PCIEInfo holds detailed PCIe slot usage information for a VM.
type PCIEInfo struct {
	TotalPorts int `json:"total_ports"` // Total pcie-root-port count
	UsedPorts  int `json:"used_ports"`  // Occupied/used ports
	FreePorts  int `json:"free_ports"`  // Free/available ports
}

// GetVMPCIEInfo returns detailed PCIe slot usage (total/used/free) for a VM.
// For running VMs, it queries QEMU monitor for accurate free bus information.
// For stopped VMs, it parses the inactive XML to count devices on PCIe buses.
// Returns (nil, nil) for non-PCIe machines (i440fx etc.).
func GetVMPCIEInfo(vmName string) (*PCIEInfo, error) {
	// Get total port count from inactive XML
	xmlStr, err := libvirt_rpc.GetDomainXMLRPC(vmName, libvirt.DomainXMLInactive)
	if err != nil {
		return nil, fmt.Errorf("获取虚拟机 XML 失败: %w", err)
	}
	if !hasPCIERootController(xmlStr) {
		// non-PCIe machine
		return nil, nil
	}

	totalPorts := 0
	for _, line := range strings.Split(xmlStr, "\n") {
		if strings.Contains(line, `<controller type='pci'`) && strings.Contains(line, `model='pcie-root-port'`) {
			totalPorts++
		}
	}

	state, _ := libvirt_rpc.GetDomainStateRPC(vmName)
	var usedPorts int

	if state == "running" {
		// For running VMs: use QEMU monitor to find free buses
		freeBuses := make([]int, 0)
		infoPCIResult, err := libvirt_rpc.QemuMonitorCommandRPC(vmName, "info pci", libvirt_rpc.DomainQemuMonitorCommandHmp)
		if err == nil {
			freeBuses = parseFreePCIERootPortBuses(infoPCIResult)
		}
		freePorts := len(freeBuses)
		usedPorts = totalPorts - freePorts
		if usedPorts < 0 {
			usedPorts = 0
		}
	} else {
		// For stopped VMs: count devices with PCI addresses in the XML
		// (excluding the pcie-root-port controllers themselves)
		devAddrCount := 0
		for _, line := range strings.Split(xmlStr, "\n") {
			trimmed := strings.TrimSpace(line)
			// Match <address type='pci' ...> but skip controller devices (pcie-root-port, pcie-root, etc.)
			if strings.Contains(trimmed, `<address type='pci'`) &&
				!strings.Contains(trimmed, `<controller`) {
				devAddrCount++
			}
		}
		usedPorts = devAddrCount
		if usedPorts > totalPorts {
			usedPorts = totalPorts
		}
	}

	freePorts := totalPorts - usedPorts
	if freePorts < 0 {
		freePorts = 0
	}

	return &PCIEInfo{
		TotalPorts: totalPorts,
		UsedPorts:  usedPorts,
		FreePorts:  freePorts,
	}, nil
}

const maxPCIERootPorts = 32

// SetVMPCIERootPorts modifies the number of pcie-root-ports reserved for a VM (requires shutdown).
// targetCount is the desired total number of pcie-root-ports (excluding pcie-root itself).
// When targetCount is 0, all existing extra pcie-root-ports are removed from XML.
func SetVMPCIERootPorts(vmName string, targetCount int) error {
	if err := EnsureNotMigrating(vmName, "修改 PCIe 端口数"); err != nil {
		return err
	}
	state, _ := libvirt_rpc.GetDomainStateRPC(vmName)
	if state == "running" {
		return fmt.Errorf("修改 PCIe 端口数量需要先关机")
	}

	xmlResult, err := libvirt_rpc.GetDomainXMLRPC(vmName, libvirt.DomainXMLInactive)
	if err != nil {
		return fmt.Errorf("获取虚拟机 XML 失败: %w", err)
	}
	if !hasPCIERootController(xmlResult) {
		return fmt.Errorf("当前虚拟机不是 PCIe (q35/virt) 机型，不需要手动管理 pcie-root-port")
	}

	// parse XML, identify system ports (auto-generated by libvirt) and extra ports (we reserved)
	lines := strings.Split(xmlResult, "\n")

	// find all pcie-root-port controller blocks
	type portBlock struct {
		index     int
		startLine int
		endLine   int
		isExtra   bool // true = extra reserved empty port (no downstream device)
	}
	var portBlocks []portBlock

	inPort := false
	currentPort := portBlock{}
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.Contains(trimmed, `<controller type='pci'`) && strings.Contains(trimmed, `model='pcie-root-port'`) {
			inPort = true
			currentPort = portBlock{startLine: i}
			// extract index attribute
			if idxMatch := regexp.MustCompile(`index='(\d+)'`).FindStringSubmatch(trimmed); len(idxMatch) > 1 {
				currentPort.index, _ = strconv.Atoi(idxMatch[1])
			}
			continue
		}

		if inPort {
			if strings.Contains(trimmed, "</controller>") {
				currentPort.endLine = i
				// determine if it's an extra reserved port: target chassis value is higher than system port range
				// system auto-generated ports have chassis around 1-7, extra reserved ones have higher values
				portBlocks = append(portBlocks, currentPort)
				inPort = false
				currentPort = portBlock{}
			}
		}
	}

	if len(portBlocks) == 0 {
		return fmt.Errorf("未找到 pcie-root-port 控制器")
	}

	currentCount := len(portBlocks)
	if currentCount == targetCount {
		return nil // no change needed
	}

	if targetCount > maxPCIERootPorts {
		return fmt.Errorf("PCIe 热插槽数量最大支持 %d 个，请输入 1 - %d 范围内的数值", maxPCIERootPorts, maxPCIERootPorts)
	}

	if targetCount > currentCount {
		// add ports: append new ports after the last pcie-root-port
		lastPortBlock := portBlocks[len(portBlocks)-1]
		insertPos := lastPortBlock.endLine + 1

		nextIndex := lastPortBlock.index + 1
		nextChassis := lastPortBlock.index + 1
		// infer next slot and function from the last <address>
		lastAddrLines := lines[lastPortBlock.startLine:lastPortBlock.endLine]
		nextSlot := 2 // default slot on pcie-root
		nextFn := 0   // function number

		for _, l := range lastAddrLines {
			if strings.Contains(l, "slot=") {
				if slotMatch := regexp.MustCompile(`slot='0x([0-9a-f]+)'`).FindStringSubmatch(l); len(slotMatch) > 1 {
					s, _ := strconv.ParseInt(slotMatch[1], 16, 64)
					nextSlot = int(s)
				}
			}
			if strings.Contains(l, "function=") {
				if fnMatch := regexp.MustCompile(`function='0x([0-9a-f]+)'`).FindStringSubmatch(l); len(fnMatch) > 1 {
					f, _ := strconv.ParseInt(fnMatch[1], 16, 64)
					nextFn = int(f) + 1
				}
			}
		}
		// when function exceeds 7, move to next slot
		if nextFn > 7 {
			nextSlot++
			nextFn = 0
		}

		// generate new empty port XML
		var newPorts []string
		currentSlot := nextSlot
		currentFn := nextFn
		for i := 0; i < targetCount-currentCount; i++ {
			idx := nextIndex + i
			chs := nextChassis + i

			newPort := fmt.Sprintf(
				`    <controller type='pci' index='%d' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='%d' port='0x%x'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x%02x' function='0x%x'/>
    </controller>`,
				idx, chs, 0x10+idx, currentSlot, currentFn)

			newPorts = append(newPorts, newPort)

			// next function, wrap slot at 8
			currentFn++
			if currentFn > 7 {
				currentSlot++
				currentFn = 0
			}
		}

		newLines := make([]string, 0, len(lines)+len(newPorts))
		newLines = append(newLines, lines[:insertPos]...)
		newLines = append(newLines, newPorts...)
		newLines = append(newLines, lines[insertPos:]...)
		lines = newLines

	} else {
		// remove ports: delete extra empty ports from the end
		removeCount := currentCount - targetCount
		removed := 0
		for i := len(portBlocks) - 1; i >= 0 && removed < removeCount; i-- {
			block := portBlocks[i]
			// skip system-critical ports (index 0-6 are usually system-generated)
			if block.index <= 6 && removed >= removeCount {
				break
			}
			// mark lines for deletion
			for j := block.startLine; j <= block.endLine; j++ {
				lines[j] = "" // placeholder deletion
			}
			removed++
		}
		if removed < removeCount {
			return fmt.Errorf("无法删除足够的端口：请求减少 %d 个，但只能安全删除 %d 个（index>6 的空端口）。请先关机后通过 virsh edit 手动调整", removeCount, removed)
		}
	}

	newXML := strings.Join(lines, "\n")
	// compress consecutive empty lines
	emptyLineRe := regexp.MustCompile(`\n\s*\n\s*\n`)
	newXML = emptyLineRe.ReplaceAllString(newXML, "\n\n")

	if _, err := libvirt_rpc.DefineDomainXMLRPC(newXML); err != nil {
		return fmt.Errorf("修改 PCIe 端口数量失败: %w", err)
	}

	return nil
}

// GetVMPCIERootPorts returns the current number of pcie-root-ports for a VM.
func GetVMPCIERootPorts(vmName string) (int, error) {
	xmlStr, err := libvirt_rpc.GetDomainXMLRPC(vmName, libvirt.DomainXMLInactive)
	if err != nil {
		return 0, fmt.Errorf("获取虚拟机 XML 失败: %w", err)
	}
	if !hasPCIERootController(xmlStr) {
		return 0, nil // non-PCIe machine, return 0
	}

	count := 0
	for _, line := range strings.Split(xmlStr, "\n") {
		if strings.Contains(line, `<controller type='pci'`) && strings.Contains(line, `model='pcie-root-port'`) {
			count++
		}
	}
	return count, nil
}

func hasSCSIController(xmlContent string) bool {
	return strings.Contains(xmlContent, "<controller type='scsi'") ||
		strings.Contains(xmlContent, `<controller type="scsi"`)
}

func buildHotplugSCSIControllerXML(vmName, xmlContent string) (string, error) {
	if !hasPCIERootController(xmlContent) {
		return "<controller type='scsi' model='virtio-scsi'/>", nil
	}

	freeBus, err := findFreePCIERootPortBus(vmName)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf(
		"<controller type='scsi' model='virtio-scsi'><address type='pci' domain='0x0000' bus='0x%02x' slot='0x00' function='0x0'/></controller>",
		freeBus,
	), nil
}

func hasPCIERootController(xmlContent string) bool {
	return strings.Contains(xmlContent, "model='pcie-root'") ||
		strings.Contains(xmlContent, `model="pcie-root"`)
}

func findFreePCIERootPortBus(vmName string) (int, error) {
	infoPCIResult, err := libvirt_rpc.QemuMonitorCommandRPC(vmName, "info pci", libvirt_rpc.DomainQemuMonitorCommandHmp)
	if err != nil {
		return 0, fmt.Errorf("获取运行中虚拟机 PCI 拓扑失败: %w", err)
	}

	freeBuses := parseFreePCIERootPortBuses(infoPCIResult)
	if len(freeBuses) == 0 {
		return 0, fmt.Errorf("当前虚拟机没有空闲的 pcie-root-port 热插槽，请先关机后再添加磁盘或光驱")
	}

	return freeBuses[len(freeBuses)-1], nil
}

func parseFreePCIERootPortBuses(infoPCI string) []int {
	rootPortBusRegex := regexp.MustCompile(`secondary bus (\d+)`)
	busHeaderRegex := regexp.MustCompile(`Bus\s+(\d+),\s+device\s+\d+,\s+function\s+\d+:`)

	available := make(map[int]bool)
	used := make(map[int]bool)

	lines := strings.Split(infoPCI, "\n")
	for _, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		if line == "" {
			continue
		}

		if strings.Contains(line, "PCI bridge: PCI device 1b36:000c") {
			continue
		}

		if match := rootPortBusRegex.FindStringSubmatch(line); len(match) >= 2 {
			bus, err := strconv.Atoi(match[1])
			if err == nil && bus > 0 {
				available[bus] = true
			}
			continue
		}

		if match := busHeaderRegex.FindStringSubmatch(line); len(match) >= 2 {
			bus, err := strconv.Atoi(match[1])
			if err == nil && bus > 0 {
				used[bus] = true
			}
		}
	}

	for bus := range used {
		delete(available, bus)
	}

	if len(available) == 0 {
		return nil
	}

	result := make([]int, 0, len(available))
	for bus := range available {
		result = append(result, bus)
	}
	sort.Ints(result)
	return result
}
